version: '3.4'

services:
  identity_api:
    container_name: "identity.api"
    image: ${DOCKER_REGISTRY-}identity.api
    build:
      context: .
      dockerfile: /src/Identity.api/Dockerfile
    networks:
      - backend-network
    ports:
      - "5000:443"
      - "5001:80"

networks:
  backend-network:
    name: "backend"